spring:
  application:
    name: springboot-discovery-service-example
  cloud:
    consul:
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
      host: consul-ui
      port: 80
