server:
  port: 9999
spring:
  application:
    name: springboot-discovery-service-example
  cloud:
    consul:
      discovery:
        enabled: true
        instance-id: m-${spring.application.name}:${server.port}
        prefer-ip-address: true
        tags: version=1,NODEFLAG=gray
      host: ${DISCOVERY_SERVICE_HOST:localhost}
      port: ${DISCOVERY_SERVICE_PORT:8500}
